DJANGO/hw_project/hw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("quotes.urls")),
    path('users/', include("users.urls"))
]

DJANGO/hw_project/quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="root"),
    path("<int:page>", views.main, name="root_paginate"),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('author/<str:author_id>/', views.author_detail),
    path('tag/<int:tag_id>/', views.quotes_by_tag, name='quotes_by_tag'),
    path('top-ten-tags/', views.top_ten_tags, name='top_ten_tags'),
]

DJANGO/hw_project/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

DJANGO/hw_project/quotes/models.py
from django.db import models
from django.contrib.auth.models import User

class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    
    def __str__(self):
        return f"{self.name}"
    

class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
   
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'name'], name='tag of username')
        ]
    def __str__(self):
        return f"{self.name}"


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag, related_name='quotes')  
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

DJANGO/hw_project/users/models.py
from django.db import models

# Create your models here.

DJANGO/hw_project/quotes/forms.py
from django import forms
from .models import Author, Quote, Tag

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

class QuoteForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all())

    class Meta:
        model = Quote
        fields = ['quote', 'tags']

DJANGO/hw_project/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    email = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

DJANGO/hw_project/quotes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from .models import Tag
from .models import Author, Quote
from .forms import AuthorForm, QuoteForm
from django.contrib.auth.decorators import login_required
from django.db.models import Count



def main(request, page=1):
    quotes = Quote.objects.all().order_by('id')
    per_page = 10
    paginator = Paginator(quotes, per_page)
    quotes_on_page = paginator.page(page)

    return render(request, "quotes/index.html", context={"quotes": quotes_on_page, "quote": quotes})

@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            author = form.save(commit=False)
            author.user = request.user  
            author.save()
            return redirect(to='quotes:root')
    else:
        form = AuthorForm()
    return render(request, 'quotes/add_author.html', {'form': form})


@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            quote = form.save(commit=False)
            quote.author = Author.objects.get(user=request.user)  
            quote.save()
            form.save_m2m()  
            return redirect(to='quotes:root') 
    else:
        form = QuoteForm()
    return render(request, 'quotes/add_quote.html', {'form': form})

def author_detail(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'quotes/author_detail.html', {'author': author})

def quotes_by_tag(request, tag_id):
    tag = Tag.objects.get(id=tag_id)
    quotes = tag.quote_set.all()
    return render(request, 'quotes/quotes_by_tag.html', {'tag': tag, 'quotes': quotes})

def top_ten_tags(request):
    top_tags = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:10]
    return render(request, 'quotes/top_ten_tags.html', {'top_tags': top_tags})

DJANGO/hw_project/users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from .forms import RegisterForm
from django.contrib.auth.views import PasswordResetView
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


from .forms import RegisterForm, LoginForm


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:root')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
       return redirect(to='quotes:root')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotes:root')

    return render(request, 'users/login.html', context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotes:root')


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

DJANGO/hw_project/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Fullname:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label>Born Date:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label>Born Location:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label>Description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

DJANGO/hw_project/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
        <label>Tags:
            {{ form.tags }}
        </label>
        <span>{{ form.errors.tags }}</span>
    </div>
    <div style="padding: 10px">
        <label>Author:
            {{ form.author }}
        </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

DJANGO/hw_project/quotes/templates/quotes/author_detail.html
{% extends 'quotes/base.html' %}

{% block content %}

<div class="author-details">
    <h3 class="author-title">{{ author.fullname }}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{ author.born_date }}</span> <span
            class="author-born-location">{{ author.born_location }}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{ author.description }}
    </div>
</div>

{% endblock %}

DJANGO/hw_project/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Homework</title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary">Add Quote</a>
                    <a href="{% url 'quotes:add_author' %}" class="btn btn-primary">Add Author</a>
                </p>
                <p>
                    {% if user.is_authenticated %}
                        <a href="{% url 'users:logout' %}" class="btn btn-primary">Log out</a>
                    {% else %}
                        <a href="{% url 'users:signup' %}" class="btn btn-primary">Register</a>
                        <a href="{% url 'users:login' %}" class="btn btn-primary">Log in</a>
                    {% endif %}
                </p>
            </div>
        </div>
        {% block top_ten_tags %}
        {% include 'quotes/top_ten_tags.html' %}
        {% endblock %}
        {% block content %} {% endblock %}
    </div>    
</body>
</html>

DJANGO/hw_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}


{% block content %}

<div class="row">
    <div class="col-md-8">
    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">
            {{quote.quote}}
        </span>
         <span>by <small class="author" itemprop="author">{{ quote.author.fullname }}</small>
                <a href="/author/{{quote.author.id}}">(about)</a>
            </span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags.all %}
            <a class="tag" href="/tag/{{ tag }}">{{ tag }}</a>
            {% endfor %}
    
        </div>
    </div>
    
    {% endfor %}
    <nav>
        <ul class="pager">
            
            <li class="previous">
                <a class= "{% if not quotes.has_previous %} disabled {% endif %}"
                    href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous</a>
            </li>
            
            
            <li class="next">
                <a class= "{% if not quotes.has_next %} disabled {% endif %}"
                href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                Next <span aria-hidden="true">→</span></a>
            </li>
            
        </ul>
    </nav>
    
</div>

{% endblock %}

DJANGO/hw_project/quotes/templates/quotes/quotes_by_tag.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        <h2>Quotes with tag: {{ tag.name }}</h2>
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{ quote.quote }}</span>
            <span>by <small class="author" itemprop="author">{{ quote.author.fullname }}</small>
                <a href="/author/{{ quote.author.id }}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="/tag/{{ tag.id }}">{{ tag.name }}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

DJANGO/hw_project/quotes/templates/quotes/top_ten_tags.html
{% block top_ten_tags %}
<div class="col-md-4 tags-box">
        
    <h2>Top Ten tags</h2>
    
    <ul> <span class="top-tags">
        {% for tag in top_tags %}
             <a class="tag" style="font-size: 28px" href="/tag/{{ tag.id }}">{{ tag.name }}</a>
         {% endfor %}
        </span>
</div>
{% endblock %}

DJANGO/hw_project/users/templates/users/login.html
{% extends "quotes/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
    <div class="small text-center">
        <a href="{% url "users:password_reset" %}" class="text-center"><i>Forgot Password?</i></a>
    </div>
</form>

{% endblock %}

DJANGO/hw_project/users/templates/users/password_reset.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

DJANGO/hw_project/users/templates/users/password_reset_complete.html
{% extends "quotes/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

DJANGO/hw_project/users/templates/users/password_reset_confirm.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

DJANGO/hw_project/users/templates/users/password_reset_done.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

DJANGO/hw_project/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

DJANGO/hw_project/users/templates/users/signup.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <div>
        <label> Email:
            {{ form.email }}
        </label>
        <span>{{ form.errors.email }}</span>
    </div>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}